// ============================================================
// Pixel Insights — Core Type Definitions
// ============================================================

/** System health states derived from Lighthouse scores */
export enum SystemState {
  STABLE = "STABLE",
  CHAOS = "CHAOS",
  FIRE = "FIRE",
}

/** Raw Lighthouse metric data */
export interface LighthouseMetrics {
  performanceScore: number; // 0–100
  fcp: number; // First Contentful Paint (ms)
  lcp: number; // Largest Contentful Paint (ms)
  cls: number; // Cumulative Layout Shift
  tbt: number; // Total Blocking Time (ms)
  timestamp: number; // Unix timestamp
  url: string; // Target URL
}

/** Interpreted snapshot used by the simulation */
export interface SystemSnapshot {
  state: SystemState;
  metrics: LighthouseMetrics;
  previousState: SystemState | null;
  transitionTriggered: boolean;
  instabilityFactor: number; // 0–1, composite instability
  events: SystemEvent[];
}

/** Agent roles in the data center */
export enum AgentRole {
  PERFORMANCE_LEAD = "Performance Lead",
  SRE = "SRE",
  INFRA_ENGINEER = "Infra Engineer",
  NETWORK_SPECIALIST = "Network Specialist",
  SYSTEM_ANALYST = "System Analyst",
  DBA = "DBA",
  FIREFIGHTER = "Firefighter",
}

/** Agent behavioral state */
export enum AgentState {
  IDLE = "IDLE",
  WORKING = "WORKING",
  ALERT = "ALERT",
  RUNNING = "RUNNING",
  FIREFIGHTING = "FIREFIGHTING",
  SCANNING = "SCANNING",
}

/** An agent in the simulation */
export interface Agent {
  id: string;
  role: AgentRole;
  state: AgentState;
  currentTask: string;
  x: number;
  y: number;
  targetX: number;
  targetY: number;
  animationFrame: number;
  direction: "down" | "up" | "left" | "right";
  speed: number;
  dialogue?: string;
  dialogueTimer: number;
  isSitting: boolean;
  homeX: number;
  homeY: number;
  // Physical attributes for diversity
  skinColor: string;
  hairColor: string;
  bodyType: "slim" | "normal" | "large";
  isWoman: boolean;
  bio?: string;
  skills?: string[];
}

/** System event generated by the event engine */
export interface SystemEvent {
  id: string;
  message: string;
  severity: "info" | "warning" | "critical";
  timestamp: number;
  metric?: string;
}

/** Historical entry for the timeline */
export interface HistoryEntry {
  snapshot: SystemSnapshot;
  timestamp: number;
}

/** Tile types for the data-center map */
export enum TileType {
  FLOOR = 0,
  SERVER = 1,
  DESK = 2,
  PLANT = 3,
  CABLE_H = 4,
  CABLE_V = 5,
  LIGHT = 6,
  WALL_TOP = 7,
  WALL_LEFT = 8,
  WALL_RIGHT = 9,
  WALL_BOTTOM = 10,
  DOOR = 11,
  MONITOR = 12,
  CHAIR = 13,
  RACK = 14,
  CORNER_TL = 15,
  CORNER_TR = 16,
  CORNER_BL = 17,
  CORNER_BR = 18,
  COFFEE_MACHINE = 19,
  WATER_COOLER = 20,
  SERVER_LARGE = 21,
  WINDOW = 22,
  CARPET = 23,
  WASTE_BIN = 24,
  WHITEBOARD = 25,
  BOXES = 26,
  LAPTOP = 27,
  SLIDING_DOOR = 28,
  SIGN_BLUE = 29,
  WALL_MONITOR = 30,
  FIRE_EXTINGUISHER = 31,
}

/** Configuration thresholds */
export interface ThresholdConfig {
  stableMin: number; // Score >= this = STABLE
  chaosMin: number; // Score >= this & < stableMin = CHAOS
  clsWarning: number; // CLS threshold for instability
  tbtWarning: number; // TBT threshold for instability (ms)
  pollInterval: number; // Seconds between Lighthouse runs
}

/** Default thresholds */
export const DEFAULT_THRESHOLDS: ThresholdConfig = {
  stableMin: 90,
  chaosMin: 50,
  clsWarning: 0.1,
  tbtWarning: 300,
  pollInterval: 30,
};
